# Generated by Django 5.2.1 on 2025-08-21 21:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ale', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la alergia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descripción')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Activo'), (2, 'Inactivo')], null=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_cat', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre de la categoría')),
                ('esta_cat', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_clin', models.CharField(max_length=100, verbose_name='Nombre de la clínica')),
                ('direc_clin', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telf_clin', models.BigIntegerField(verbose_name='Teléfono')),
                ('email_clin', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
                ('photo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Foto (ruta)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(default='S', max_length=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('honorariosPorcentaje', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('tipo_doc', models.CharField(max_length=50, verbose_name='Tipo de documento')),
                ('num_doc', models.CharField(max_length=50, unique=True, verbose_name='Número de documento')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='Foto de perfil')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('rol', models.CharField(choices=[('medico', 'Médico'), ('admin', 'Administrador'), ('enfermero', 'Enfermero/a')], max_length=50, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidad')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreConsultorio', models.CharField(default='', max_length=100)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_pac', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombres')),
                ('apel_pac', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellidos')),
                ('edad_pac', models.CharField(blank=True, max_length=3, null=True, verbose_name='Edad')),
                ('ocupacion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ocupación')),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Lugar de nacimiento')),
                ('informacion_clinica', models.CharField(blank=True, max_length=70, null=True, verbose_name='Información clínica')),
                ('dire_pac', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('telf_pac', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('dni_pac', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='DNI')),
                ('foto_paciente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Foto (ruta)')),
                ('fena_pac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro')),
                ('civi_pac', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado civil')),
                ('afil_pac', models.CharField(blank=True, max_length=30, null=True, verbose_name='Afiliación')),
                ('aler_pac', models.CharField(blank=True, max_length=120, null=True, verbose_name='Alergias')),
                ('emai_pac', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo electrónico')),
                ('titu_pac', models.CharField(blank=True, max_length=20, null=True, verbose_name='Titular')),
                ('pais_id', models.IntegerField(blank=True, null=True, verbose_name='ID país')),
                ('departamento_id', models.IntegerField(blank=True, null=True, verbose_name='ID departamento')),
                ('provincia_id', models.IntegerField(blank=True, null=True, verbose_name='ID provincia')),
                ('distrito_id', models.IntegerField(blank=True, null=True, verbose_name='ID distrito')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('registro_pac', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Registro paciente')),
                ('detalleodontograma_pac', models.TextField(blank=True, null=True, verbose_name='Detalle Odontograma')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='MASCULINO', max_length=100)),
                ('esta_pac', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8, verbose_name='Estado')),
                ('estudios_pac', models.CharField(choices=[('NINGUNO', 'Ninguno'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TECNICO', 'Tecnico'), ('UNIVERSITARIO', 'Universitario')], default='SECUNDARIA', max_length=100, verbose_name='Estudios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelado', models.BooleanField(default=False)),
                ('reprogramado', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('reminder_sent', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.consultorio')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alergia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enfermedad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enfermedad')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidad')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacientePlaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True, max_length=1000, null=True)),
                ('archivo', models.ImageField(null=True, upload_to='')),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(default='tratamiento', max_length=200)),
                ('observacion', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
    ]
