# Generated by Django 5.2.1 on 2025-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='medico',
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico'), ('admin', 'Administrador'), ('enfermero', 'Enfermero/a')], max_length=50, verbose_name='Rol'),
        ),
    ]
