# Generated by Django 5.2.1 on 2025-08-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
