# Generated by Django 5.2.1 on 2025-06-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_medico_alter_user_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ale', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la alergia')),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descripción')),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Activo'), (2, 'Inactivo')], null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_cat', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre de la categoría')),
                ('esta_cat', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_clin', models.CharField(max_length=100, verbose_name='Nombre de la clínica')),
                ('direc_clin', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telf_clin', models.BigIntegerField(verbose_name='Teléfono')),
                ('email_clin', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
                ('ruc_clin', models.CharField(blank=True, max_length=15, null=True, verbose_name='RUC')),
                ('fecha_clin', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('photo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Foto (ruta)')),
                ('cod_plan', models.IntegerField(verbose_name='Código de plan')),
                ('esta_clin', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(default='S', max_length=1, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nac',
            new_name='fena_pac',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono',
            new_name='telf_pac',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='num_doc',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_doc',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='cita',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='afil_pac',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Afiliación'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='aler_pac',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apel_pac',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='civi_pac',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='departamento_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID departamento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='detalleodontograma_pac',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Odontograma'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dire_pac',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='distrito_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID distrito'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dni_pac',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad_pac',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='emai_pac',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='esta_pac',
            field=models.CharField(default='S', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estudios_pac',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estudios'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_paciente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foto (ruta)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='informacion_clinica',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Información clínica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nomb_pac',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pais_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID país'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='provincia_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID provincia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='registro_pac',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Registro paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo_pac',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='titu_pac',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='fechaVencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='MASCULINO', max_length=100),
        ),
        migrations.CreateModel(
            name='PacienteAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(max_length=200)),
                ('alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alergia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enfermedad')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidad')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
                ('tratamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='pagos',
            name='pacienteTratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pacientetratamiento'),
        ),
    ]
