# Generated by Django 5.2.1 on 2025-09-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enfermedad_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='old_cod_cit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='old_cod_pac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='old_cod_med',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
