# Generated by Django 5.2.1 on 2025-09-08 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cita_old_cod_cit_paciente_old_cod_pac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidad'),
        ),
    ]
