# Generated by Django 5.2.1 on 2025-06-21 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alergia_banco_categoria_clinica_enfermedad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sexo_pac',
        ),
        migrations.AddField(
            model_name='alergia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alergia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pacientealergia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientealergia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='esta_pac',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estudios_pac',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TECNICO', 'Tecnico'), ('UNIVERSITARIO', 'Universitario')], default='SECUNDARIA', max_length=100, verbose_name='Estudios'),
        ),
    ]
