# Generated by Django 5.2.1 on 2025-07-07 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_paciente_sexo_pac_alergia_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='honorariosPorcentaje',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
    ]
