# Generated by Django 5.2.1 on 2025-09-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='paciente',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(default='s', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='precioBase',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TratamientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(default='tratamiento', max_length=200)),
                ('observacion', models.TextField(blank=True, max_length=1000, null=True)),
                ('descuento', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tratamiento')),
            ],
        ),
    ]
