# Generated by Django 5.2.1 on 2025-07-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_especialidad_honorariosporcentaje_delete_pagos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientetratamiento',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='pacientetratamiento',
            name='tratamiento',
        ),
    ]
