# Generated by Django 5.2.1 on 2025-07-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pacientetratamiento_paciente_and_more'),
        ('transactions', '0002_remove_pagos_pacientetratamiento_pagos_cita_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacienteTratamiento',
        ),
    ]
