# Generated by Django 5.2.1 on 2025-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoriatratamiento_tratamiento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='precioConvenio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tratamientopaciente',
            name='convenio',
            field=models.BooleanField(default=False),
        ),
    ]
