# Generated by Django 5.2.1 on 2025-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tratamiento_precioconvenio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientopaciente',
            name='descuento_porcentaje',
            field=models.BooleanField(default=True),
        ),
    ]
