# Generated by Django 5.2.1 on 2025-07-31 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_pacientetratamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='asunto',
            field=models.CharField(default='tratamiento', max_length=200),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='observacion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PacienteDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enfermedad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacientePlaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('notas', models.TextField(max_length=1000, null=True)),
                ('archivo', models.ImageField(null=True, upload_to='')),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
