# Generated by Django 5.2.1 on 2025-10-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tratamientopaciente_descuento_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tratamiento'),
        ),
    ]
