# Generated by Django 5.2.1 on 2025-08-02 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cita_tratamiento_remove_tratamiento_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='costo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='pagado',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='saldo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='honorariosPorcentaje',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
