# Generated by Django 5.2.1 on 2025-10-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cita_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_especialista',
            field=models.BooleanField(default=False, verbose_name='¿Es especialista?'),
        ),
    ]
