# Generated by Django 5.2.1 on 2025-08-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cita_motivo_cita_observaciones_alter_cita_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='estadoPago',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='saldo',
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pacientealergia',
            name='observacion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pacienteplaca',
            name='notas',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
