# Generated by Django 5.2.1 on 2025-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_is_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientopaciente',
            name='descuento_porcentaje',
            field=models.BooleanField(default=False),
        ),
    ]
