# Generated by Django 5.2.1 on 2025-12-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tratamientopaciente_descuento_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
