# Generated by Django 5.2.1 on 2026-01-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clinica_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientopaciente',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
