# Generated by Django 5.2.1 on 2026-03-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_tratamientopaciente_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='convenio_pac',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('PETROPERU', 'Petroperú'), ('OTRO', 'Otro')], default='PARTICULAR', max_length=20, verbose_name='Convenio'),
        ),
    ]
