# Generated by Django 5.2.1 on 2026-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_paciente_convenio_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='convenio_pac',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('PETROPERU', 'Petroperú'), ('MAPFRE', 'Mapfre'), ('PROTECTORA', 'Protectora'), ('COLEGIO DE INGENIEROS', 'Colegio de Ingenieros'), ('LOS ARBOLITOS', 'Los Arbolitos'), ('COLEGIO DE OBSTETRAS', 'Colegio de Obstetras'), ('COLEGIO CERSAR VALLEJO', 'Colegio César Vallejo'), ('COLEGIO DE ABOGADOS', 'Colegio de Abogados'), ('MOTOMAQ', 'Motomaq'), ('OTRO', 'Otro')], default='PARTICULAR', max_length=50, verbose_name='Convenio'),
        ),
    ]
