# Generated by Django 5.2.1 on 2026-04-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_paciente_convenio_pac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni_pac',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='DNI'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('dni_pac', 'clinica'), name='unique_dni_pac_per_clinica'),
        ),
    ]
