# Generated by Django 5.2.1 on 2026-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_paciente_dni_pac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='anotacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
