# Generated by Django 5.2.1 on 2026-07-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cita_anotacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='control_limit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='monthly_control_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profilaxis_limit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profilaxis_scheduled',
            field=models.BooleanField(default=False, verbose_name='Profilaxis Programada'),
        ),
    ]
