# Generated by Django 5.2.1 on 2025-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='current_sub_state',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='data_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='current_state',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
