# Generated by Django 5.2.1 on 2025-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chat_current_sub_state_chat_data_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
