# Generated by Django 5.2.1 on 2025-12-30 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chat_extra_data'),
        ('core', '0012_clinica_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('texto_original', models.TextField()),
                ('sentimiento', models.CharField(choices=[('POSITIVE', 'Positivo'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negativo')], default='NEUTRAL', max_length=20)),
                ('aspectos_positivos', models.TextField(blank=True, help_text='JSON list of what they liked')),
                ('areas_mejora', models.TextField(blank=True, help_text='JSON list of complaints/improvements')),
                ('sugerencias', models.TextField(blank=True)),
                ('requiere_atencion_humana', models.BooleanField(default=False, help_text='True if sentiment is negative or asks for help')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='core.paciente')),
            ],
        ),
    ]
