# Generated by Django 5.2.1 on 2025-09-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='cita',
        ),
    ]
