# Generated by Django 5.2.1 on 2025-07-17 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pacientetratamiento_paciente_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='pacienteTratamiento',
        ),
        migrations.AddField(
            model_name='pagos',
            name='cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cita'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='metodo',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
        migrations.DeleteModel(
            name='Honorarios',
        ),
    ]
