# Generated by Django 5.2.1 on 2025-09-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoriatratamiento_tratamiento_categoria'),
        ('transactions', '0002_remove_ingreso_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='paciente',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='tratamientoPaciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tratamientopaciente'),
        ),
    ]
