# Generated by Django 5.2.1 on 2025-10-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tratamientopaciente_descuento_porcentaje'),
        ('transactions', '0003_remove_ingreso_paciente_ingreso_tratamientopaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='tratamientoPaciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='core.tratamientopaciente'),
        ),
    ]
