# Generated by Django 5.2.1 on 2025-10-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_ingreso_tratamientopaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='metodo',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=50),
        ),
    ]
