# Generated by Django 5.2.1 on 2025-10-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_is_especialista'),
        ('transactions', '0005_alter_ingreso_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='tratamientoPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tratamientopaciente'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
    ]
