# Generated by Django 5.2.1 on 2025-10-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tratamientopaciente_descuento_porcentaje'),
        ('transactions', '0006_egreso_fecha_registro_egreso_tratamientopaciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinica'),
        ),
    ]
