# Generated by Django 5.2.1 on 2026-01-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_egreso_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='porcentaje_medico',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
