# Generated by Django 5.2.1 on 2026-01-24 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_ingreso_porcentaje_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='source_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_egresos', to='transactions.ingreso'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='tipo',
            field=models.CharField(choices=[('LAB', 'Laboratorio'), ('DOC', 'Pago Medico'), ('CLI', 'Clinica')], default='CLI', max_length=3),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
