# Generated by Django 5.2.1 on 2026-01-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_egreso_source_ingreso_egreso_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
