# Generated by Django 5.2.1 on 2026-02-03 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_tratamientopaciente_descuento'),
        ('transactions', '0010_alter_egreso_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinica'),
        ),
    ]
