# Generated by Django 5.2.1 on 2026-07-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_proclab_egreso_proclab_quantity_egreso_proclab'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='is_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='egreso',
            name='repetition_type',
            field=models.CharField(blank=True, choices=[('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, null=True),
        ),
    ]
