# Generated by Django 5.2.1 on 2025-08-21 21:32

import django.db.models.deletion
import odontograma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDiente', models.IntegerField()),
                ('iconoPorDefecto', models.ImageField(upload_to='odontograma/iconos_default/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificaciones', models.TextField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DienteOdontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconoModificado', models.ImageField(blank=True, null=True, upload_to='legacy_placeholder/')),
                ('datosRecuadro', models.CharField(blank=True, default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='odontograma.diente')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontograma.odontograma')),
            ],
        ),
        migrations.CreateModel(
            name='CasoMultidental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.CharField(blank=True, choices=[('TRAN', 'Transposición'), ('SUP', 'Supernumerario'), ('PTOT', 'Prótesis Total'), ('PREM', 'Prótesis Removible'), ('GFUS', 'Geminación / Fusión'), ('EDTO', 'Edéntulo Total'), ('DIA', 'Diastema'), ('AOR', 'Aparato Ortodóntico Removible'), ('AOF', 'Aparato Ortodóntico Fijo')], default=None, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dienteExtremo1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diente_extremo_1', to='odontograma.diente')),
                ('dienteExtremo2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diente_extremo_2', to='odontograma.diente')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontograma.odontograma')),
            ],
        ),
    ]
