# Generated by Django 5.2.1 on 2025-12-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casomultidental',
            name='dienteExtremo1',
        ),
        migrations.RemoveField(
            model_name='casomultidental',
            name='dienteExtremo2',
        ),
        migrations.RemoveField(
            model_name='casomultidental',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='diente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diente',
            name='iconoPorDefecto',
        ),
        migrations.RemoveField(
            model_name='diente',
            name='numeroDiente',
        ),
        migrations.RemoveField(
            model_name='diente',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='casomultidental',
            name='dienteEnd',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, related_name='caso_end', to='odontograma.diente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casomultidental',
            name='dienteStart',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, related_name='caso_start', to='odontograma.diente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casomultidental',
            name='drawing_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diente',
            name='hitbox_json',
            field=models.JSONField(default={}, help_text='Coordinates for zoom/click detection on the master map'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diente',
            name='numero',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odontograma',
            name='diagrama_json',
            field=models.JSONField(blank=True, help_text='Full canvas drawing data', null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='odontogramas/previews/'),
        ),
        migrations.AlterField(
            model_name='casomultidental',
            name='caso',
            field=models.CharField(choices=[('TRAN', 'Transposición'), ('SUP', 'Supernumerario'), ('PTOT', 'Prótesis Total'), ('PREM', 'Prótesis Removible'), ('GFUS', 'Geminación / Fusión'), ('EDTO', 'Edéntulo Total'), ('DIA', 'Diastema'), ('AOR', 'Aparato Ortodóntico Removible'), ('AOF', 'Aparato Ortodóntico Fijo'), ('PUE', 'Puente Fijo')], default='a', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casomultidental',
            name='odontograma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_multidentales', to='odontograma.odontograma'),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='especificaciones',
            field=models.TextField(blank=True, default='a', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='observaciones',
            field=models.TextField(blank=True, default='a', max_length=2000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=50)),
                ('superficie', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('GOOD', 'Bueno/Azul'), ('BAD', 'Malo/Rojo')], max_length=10)),
                ('diente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odontograma.diente')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='odontograma.odontograma')),
            ],
            options={
                'unique_together': {('odontograma', 'diente', 'condicion')},
            },
        ),
        migrations.DeleteModel(
            name='DienteOdontograma',
        ),
    ]
