# Generated by Django 5.2.1 on 2025-06-29 21:43

import odontograma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0002_diente_casomultidental_dienteodontograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienteodontograma',
            name='datosRecuadro',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dienteodontograma',
            name='iconoModificado',
            field=models.ImageField(blank=True, null=True, upload_to=odontograma.models.odontograma_upload_path),
        ),
    ]
