# Generated by Django 5.2.1 on 2025-12-18 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clinica_telegram_chat_id'),
        ('odontograma', '0002_remove_casomultidental_dienteextremo1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odontograma',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='diagrama_json',
        ),
        migrations.AddField(
            model_name='odontograma',
            name='drawings',
            field=models.JSONField(blank=True, default=dict, help_text='Normalized vector paths grouped by Tooth ID'),
        ),
        migrations.AlterField(
            model_name='odontograma',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='core.paciente'),
        ),
    ]
