# Generated by Django 5.2.1 on 2025-12-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0003_alter_odontograma_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hallazgo',
            unique_together={('odontograma', 'diente')},
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='estado',
            field=models.CharField(blank=True, choices=[('GOOD', 'Bueno/Azul'), ('BAD', 'Malo/Rojo')], max_length=10, null=True),
        ),
    ]
