# Generated by Django 5.2.1 on 2025-07-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0003_alter_dienteodontograma_datosrecuadro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='especificaciones',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='observaciones',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='dienteodontograma',
            name='datosRecuadro',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
