# Generated by Django 5.2.1 on 2025-12-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0004_alter_hallazgo_unique_together_alter_hallazgo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='multi_tooth_drawings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
